#!/bin/sh

case "$*" in
  *failing*)
    printf '%s\n' 'running 1 test'
    printf '%s\n' 'test tests::failing ... FAILED'
    printf '%s\n' ''
    printf '%s\n' 'failures:'
    printf '%s\n' ''
    printf '%s\n' '---- tests::failing stdout ----'
    printf '%s\n' "thread 'tests::failing' panicked at 'assertion failed'"
    printf '%s\n' ''
    printf '%s\n' 'test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s'
    exit 101
    ;;
  *)
    printf '%s\n' 'running 1 test'
    printf '%s\n' 'test tests::passing ... ok'
    printf '%s\n' ''
    printf '%s\n' 'test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s'
    ;;
esac
